# Ejercicios sobre diccionarios II + Ficheros

## Ejercicio 1

El fichero [localidades.txt]() contiene información de las localidades de la Comunidad de Madrid. Los datos que contiene son:
* Nombre de la localidad
* Teléfono Ayuntamiento
* Teléfono Información
* Teléfono emergencias

Aunque los teléfonos pueden no aparecer todos en el fichero.
Crear una función llamada __leer_datos__ que lea los datos del fichero y los almacene en una lista de líneas. Usa la operación __readlines__ de los ficheros. El parámetro de entrada de la función es la ruta donde se encuentra el fichero. 

La función debe devolver una lista con todos los municipio leídos en el fichero.
¿ Cuantos municipios hay en el fichero ?

__Nota__ 

Si da problemas la función `open`, usa el parámetro `encoding= "utf-8"`  para solucionarlo.

In [25]:
# Sol:  #Si tienes el fichero de localidades y la practica en el mismo fichero se puede ejecutar esta operacion
f = open('localidades.txt', encoding="utf8")
l = f.readlines()
l

['Nombre localidad|Teléfono Ayuntamiento|Teléfono Información | Teléfono emergencias\n',
 'La Acebeda|9286 |2855 |\n',
 'Ajalvir||9097 |\n',
 'El Álamo|9375 |8420 |\n',
 'Alcalá de Henares|8350 ||7261 \n',
 'Alcobendas||3115 |\n',
 'Alcorcón|||9861 \n',
 'Aldea del Fresno|||4043 \n',
 'Alpedrete|1705 |6251 |2198 \n',
 'Ambite||9037 |\n',
 'Anchuelo|4973 |5257 |\n',
 'Aranjuez||4805 |\n',
 'Arganda del Rey|3111 ||3035 \n',
 'Arroyomolinos|2926 ||8481 \n',
 'El Atazar|9650 |7157 |\n',
 'Batres|8800 |1164 |6059 \n',
 'Becerril de la Sierra||7251 |1875 \n',
 'Belmonte de Tajo|||3419 \n',
 'El Berrueco|2476 ||6650 \n',
 'Berzosa del Lozoya|4787 |2913 |2478 \n',
 'Boadilla del Monte|1428 |5557 |\n',
 'El Boalo|5632 |8008 |8019 \n',
 'Brea de Tajo|||8496 \n',
 'Brunete|3731 |8510 |\n',
 'Buitrago del Lozoya|6917 |2243 |3178 \n',
 'Bustarviejo||6323 |5048 \n',
 'Cabanillas de la Sierra||8537 |\n',
 'La Cabrera||7061 |\n',
 'Cadalso de los Vidrios|1525 ||3811 \n',
 'Camarma de Esteruelas||6306 

In [26]:
def leer_localidades ():
    f = open('localidades.txt', encoding="utf8")
    l = f.readlines() #esta l es una lista de lineas, y de cada linea SOLO ME QUEDO CON EL MUNICIPIO
    localidades = []
    for linea in l[1:]:
        datos= linea.split("|")
        localidades.append (datos[0])
    return localidades
        
#lo que le estoy pidiendo es que me parta el stream cuando se encuentre |.

In [27]:
leer_localidades()

['La Acebeda',
 'Ajalvir',
 'El Álamo',
 'Alcalá de Henares',
 'Alcobendas',
 'Alcorcón',
 'Aldea del Fresno',
 'Alpedrete',
 'Ambite',
 'Anchuelo',
 'Aranjuez',
 'Arganda del Rey',
 'Arroyomolinos',
 'El Atazar',
 'Batres',
 'Becerril de la Sierra',
 'Belmonte de Tajo',
 'El Berrueco',
 'Berzosa del Lozoya',
 'Boadilla del Monte',
 'El Boalo',
 'Brea de Tajo',
 'Brunete',
 'Buitrago del Lozoya',
 'Bustarviejo',
 'Cabanillas de la Sierra',
 'La Cabrera',
 'Cadalso de los Vidrios',
 'Camarma de Esteruelas',
 'Campo Real',
 'Canencia',
 'Carabaña',
 'Casarrubuelos',
 'Cenicientos',
 'Cercedilla',
 'Cervera de Buitrago',
 'Chapinería',
 'Chinchón',
 'Ciempozuelos',
 'Cobeña',
 'Collado Mediano',
 'Collado Villalba',
 'Colmenar de Oreja',
 'Colmenar del Arroyo',
 'Colmenar Viejo',
 'Coslada',
 'Cubas de la Sagra',
 'El Escorial',
 'Estremera',
 'Fresnedillas de la Oliva',
 'Fresno de Torote',
 'Fuenlabrada',
 'Fuente el Saz de Jarama',
 'Fuentidueña de Tajo',
 'Garganta de los Montes',
 'G

In [34]:
def leer_datos(lista):
    localidades = []
    i = 1
    while i < len(lista):
        x = lista[i].split('|')
        localidades.append(x[0:4])
        i = i + 1
    print(len(localidades))
    return (localidades)


In [38]:
localidades = leer_datos(l)

161


In [39]:
type(localidades)

list

In [41]:
localidades

[['La Acebeda', '9286 ', '2855 ', '\n'],
 ['Ajalvir', '', '9097 ', '\n'],
 ['El Álamo', '9375 ', '8420 ', '\n'],
 ['Alcalá de Henares', '8350 ', '', '7261 \n'],
 ['Alcobendas', '', '3115 ', '\n'],
 ['Alcorcón', '', '', '9861 \n'],
 ['Aldea del Fresno', '', '', '4043 \n'],
 ['Alpedrete', '1705 ', '6251 ', '2198 \n'],
 ['Ambite', '', '9037 ', '\n'],
 ['Anchuelo', '4973 ', '5257 ', '\n'],
 ['Aranjuez', '', '4805 ', '\n'],
 ['Arganda del Rey', '3111 ', '', '3035 \n'],
 ['Arroyomolinos', '2926 ', '', '8481 \n'],
 ['El Atazar', '9650 ', '7157 ', '\n'],
 ['Batres', '8800 ', '1164 ', '6059 \n'],
 ['Becerril de la Sierra', '', '7251 ', '1875 \n'],
 ['Belmonte de Tajo', '', '', '3419 \n'],
 ['El Berrueco', '2476 ', '', '6650 \n'],
 ['Berzosa del Lozoya', '4787 ', '2913 ', '2478 \n'],
 ['Boadilla del Monte', '1428 ', '5557 ', '\n'],
 ['El Boalo', '5632 ', '8008 ', '8019 \n'],
 ['Brea de Tajo', '', '', '8496 \n'],
 ['Brunete', '3731 ', '8510 ', '\n'],
 ['Buitrago del Lozoya', '6917 ', '2243 ', '31

## Ejercicio 2

Escribe una función llamada __crear_agenda__ para crear la agenda de los teléfonos de los municipios de la Comunidad de Madrid.
La función tiene un único parámetro de entrada, que es la lista de municipios devuelta por la función del Ejercicio 1. 

El valor devuelto por la función __crear_agenda__ es de tipo diccionario, donde las claves son los nombres de los municipios y el valor asociado a cada clave será otro diccionario con tantas claves como teléfonos disponibles tenga el municipio.

__Notas:__
La función deve devolver un diccionario con el siguiente aspecto:

```
{
 'La Acebeda': {'Teléfono Ayuntamiento': '9286',   'Teléfono Información': '2855'},
 'Ajalvir': {'Teléfono Información': '9097'},
 'El Álamo': {'Teléfono Ayuntamiento': '9375', 'Teléfono Información': '8420'},
 'Alcalá de Henares': {'Teléfono Ayuntamiento': '8350',   'Teléfono Emergencias': '7261'},
 'Alcobendas': {'Teléfono Información': '3115'},
    ...
    ...
 'Zarzalejo': {'Teléfono Ayuntamiento': '5046',  'Teléfono Información': '1283'}
}
```

In [11]:
d = "  Mostoles  "
d.strip()
#Para quitar los espacios en blanco. los de la derecha d.dstrip. los de la izq d.lstrip. 
#tambien me quita los saltos de linea 

'Mostoles'

In [56]:
def crear_agenda_localidades ():
    f = open('localidades.txt', encoding="utf8")
    l = f.readlines()
    agenda = {}
    for linea in l [1:]: 
        datos = linea.split("|")
        nombre = datos[0].strip() #strip: elimina saltos, espacios 
        ayunta = datos[1].strip()
        inf = datos[2].strip()
        emer = datos [3].strip()
        agenda[nombre] = {}
        if ayunta != "":
            agenda [nombre]["tel ayunt"] = ayunta 
            agenda [nombre]["tel inf"] = inf
    
    
    return agenda

In [57]:
agenda_municipios = crear_agenda_localidades()
agenda_municipios

{'La Acebeda': {'tel ayunt': '9286', 'tel inf': '2855'},
 'Ajalvir': {},
 'El Álamo': {'tel ayunt': '9375', 'tel inf': '8420'},
 'Alcalá de Henares': {'tel ayunt': '8350', 'tel inf': ''},
 'Alcobendas': {},
 'Alcorcón': {},
 'Aldea del Fresno': {},
 'Alpedrete': {'tel ayunt': '1705', 'tel inf': '6251'},
 'Ambite': {},
 'Anchuelo': {'tel ayunt': '4973', 'tel inf': '5257'},
 'Aranjuez': {},
 'Arganda del Rey': {'tel ayunt': '3111', 'tel inf': ''},
 'Arroyomolinos': {'tel ayunt': '2926', 'tel inf': ''},
 'El Atazar': {'tel ayunt': '9650', 'tel inf': '7157'},
 'Batres': {'tel ayunt': '8800', 'tel inf': '1164'},
 'Becerril de la Sierra': {},
 'Belmonte de Tajo': {},
 'El Berrueco': {'tel ayunt': '2476', 'tel inf': ''},
 'Berzosa del Lozoya': {'tel ayunt': '4787', 'tel inf': '2913'},
 'Boadilla del Monte': {'tel ayunt': '1428', 'tel inf': '5557'},
 'El Boalo': {'tel ayunt': '5632', 'tel inf': '8008'},
 'Brea de Tajo': {},
 'Brunete': {'tel ayunt': '3731', 'tel inf': '8510'},
 'Buitrago del L

## Ejercicio 3 

Escribe una función en Python llamada __consulta_telefono__ para recuperar los teléfonos disponibles de un municipio.
La función tiene dos argumentos de entrada:
1. Agenda de municipios creada por la función del ejercicio 2.
2. Nombre de un municipio

Si el nombre del municipio  no se encuentra en el diccionario, la función devuelve el valor `False`. En caso contrario, devuelve un diccionario con los teléfonos disponibles.

__Ejemplo de ejecución:__

``` 
In: 
    t = consulta_telefono('Zarzalejo', agenda_municipios)
    t
Out:
    {'Teléfono Ayuntamiento': '5046',  'Teléfono Información': '1283'}
```


In [58]:
def consulta_telefono(municipio,agenda):
    if municipio in agenda:
        return agenda[municipio]
    else:
        return False

In [59]:
t = consulta_telefono('Zarzalejo', agenda_municipios)
t


{'tel ayunt': '5046', 'tel inf': '1283'}

## Ejercicio 4

Escribe una función en Python llamada __consulta_tipo_telef__ para recuperar número de teléfono de un determinado tipo (Emergencias, Ayuntamiento o Información) de un municipio.
La función tiene tres argumentos de entrada:
1. Agenda de los municipios
2. Nombre de un municipio
3. Tipo de número de teléfono

Si el municipio no se encuentra en la agenda, la función devuelve el valor `False`. En caso contrario, devuelve su número de teléfono. Si el tipo de teléfono no existe para ese amigo, la función devuelve el valor `False`.

__Ejemplo de ejecución 1 :__

``` 
In: 
    t =  consulta_tipo_telefono('Zarzalejo', 'Teléfono Ayuntamiento', agenda_municipios)
    t
Out:
    5046
```
__Ejemplo de ejecución 2 :__
``` 
In: 
    t =  consulta_tipo_telefono('Zarzalejo', 'Teléfono Piscina', agenda_municipios)
    t
Out:
    False
```



In [64]:
def consulta_tipo_telefono(municipio, tipo_telefono, agenda):
    if municipio in agenda and tipo_telefono in agenda[municipio]:

        return agenda[municipio][tipo_telefono]
    else:
        return False

In [65]:
consulta_tipo_telefono('Zarzalejo', 'Teléfono Piscina', agenda_municipios)

False

## Ejercicio 5

Escribe una función en Python llamada __lista_municipios__ para recuperar los nombres de los municipios que se encuentrasn registrados en la agenda de teléfonos.
La función tiene un único argumento de entrada:
1. Diccionario que representa la agenda

La función ha de devolver una lista ordenada de municipios en orden lexicográfico.

__Ejemplo de ejecución:__
``` 
In: 
    a = lista_municipios(agenda)
    a
Out:
    ['Ajalvir',
     'Alcalá de Henares',
     'Alcobendas', 
     ...
     'Zarzalejo']

```

In [66]:
def lista_municipios(agenda):
    a = sorted(list(agenda))
    return a


In [67]:
lista_municipios(agenda_municipios)

['Ajalvir',
 'Alcalá de Henares',
 'Alcobendas',
 'Alcorcón',
 'Aldea del Fresno',
 'Alpedrete',
 'Ambite',
 'Anchuelo',
 'Aranjuez',
 'Arganda del Rey',
 'Arroyomolinos',
 'Batres',
 'Becerril de la Sierra',
 'Belmonte de Tajo',
 'Berzosa del Lozoya',
 'Boadilla del Monte',
 'Brea de Tajo',
 'Brunete',
 'Buitrago del Lozoya',
 'Bustarviejo',
 'Cabanillas de la Sierra',
 'Cadalso de los Vidrios',
 'Camarma de Esteruelas',
 'Campo Real',
 'Canencia',
 'Carabaña',
 'Casarrubuelos',
 'Cenicientos',
 'Cercedilla',
 'Cervera de Buitrago',
 'Chapinería',
 'Chinchón',
 'Ciempozuelos',
 'Cobeña',
 'Collado Mediano',
 'Collado Villalba',
 'Colmenar Viejo',
 'Colmenar de Oreja',
 'Colmenar del Arroyo',
 'Coslada',
 'Cubas de la Sagra',
 'El Atazar',
 'El Berrueco',
 'El Boalo',
 'El Escorial',
 'El Molar',
 'El Vellón',
 'El Álamo',
 'Estremera',
 'Fresnedillas de la Oliva',
 'Fresno de Torote',
 'Fuenlabrada',
 'Fuente el Saz de Jarama',
 'Fuentidueña de Tajo',
 'Garganta de los Montes',
 'Garg

## Ejercicio 6

Escribe una función en Python llamada __eliminar_municipio__ para eliminar los datos de un municipio de una agenda de teléfonos. Dicha agenda se representa como un diccionario. 
La función tiene tres  argumentos de entrada:
1. Diccionario que representa la agenda
2. El nombre de un municipio

La función devuelve el valor `True` si se ha eliminado correctamente. Devuelve False para indicar que el municipio no estaba en la agenda.


In [68]:
def eliminar_municipio(agenda, municipio):
    if municipio in agenda:
        agenda.pop(municipio)
        return True
    else:
        return False

In [71]:
eliminar_municipio(agenda_municipios, 'Alcalá de Henares')

True

In [72]:
eliminar_municipio(agenda_municipios, 'Vera')

False